In [15]:
import pandas as pd

In [ ]:
df = pd.read_csv('titanic.csv',usecols=['Age', 'Fare', 'Survived', 'Cabin'])
df

     Survived   Age     Fare Cabin
0         0.0  22.0   7.2500   NaN
1         NaN  38.0  71.2833   C85
2         NaN   NaN      NaN   NaN
3         NaN  35.0  53.1000  C123
4         0.0  35.0   8.0500   NaN
..        ...   ...      ...   ...
886       0.0  27.0  13.0000   NaN
887       1.0  19.0  30.0000   B42
888       0.0   NaN  23.4500   NaN
889       1.0  26.0  30.0000  C148
890       0.0  32.0   7.7500   NaN

[891 rows x 4 columns]

In [30]:
df.isnull().sum()

Survived      4
Age         178
Fare          3
Cabin       687
dtype: int64

In [32]:
df['Survived'].fillna(1, inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_22268\1838309045.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Survived'].fillna(1, inplace=True)

In [33]:
df.isnull().sum

<bound method DataFrame.sum of      Survived    Age   Fare  Cabin
0       False  False  False   True
1       False  False  False  False
2       False   True   True   True
3       False  False  False  False
4       False  False  False   True
..        ...    ...    ...    ...
886     False  False  False   True
887     False  False  False  False
888     False   True  False   True
889     False  False  False  False
890     False  False  False   True

[891 rows x 4 columns]>

In [34]:
df['Fare'].fillna(method="ffill",inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_22268\3672421889.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Fare'].fillna(method="ffill",inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_22268\3672421889.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Fare'].fillna(method="ffill",inplace=True)

In [35]:
df.isnull().sum()

Survived      0
Age         178
Fare          0
Cabin       687
dtype: int64

In [37]:
df['Cabin']=df['Cabin'].bfill()

In [38]:
print(df.isnull().sum())

Survived      0
Age         178
Fare          0
Cabin         1
dtype: int64

In [41]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [42]:
print(df.isnull().sum())

Survived    0
Age         0
Fare        0
Cabin       1
dtype: int64

In [43]:
df=pd.read_csv('titanic.csv',usecols=['Age','Fare','Survived','Cabin'])

In [44]:
df.interpolate(inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_22268\471562723.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(inplace=True)

In [45]:
df.isnull().sum()

Survived      0
Age           0
Fare          0
Cabin       687
dtype: int64

In [46]:
import pandas as pd

In [47]:
df=pd.read_csv('titanic.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0.0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,NaN,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,NaN,3,"Heikkinen, Miss. Laina",female,NaN,0,0,STON/O2. 3101282,NaN,NaN,S
3,4,NaN,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0.0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0.0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1.0,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0.0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1.0,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0.0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [48]:
df.isnull().sum()

PassengerId      0
Survived         4
Pclass           0
Name             0
Sex              0
Age            178
SibSp            0
Parch            0
Ticket           0
Fare             3
Cabin          687
Embarked         2
dtype: int64

In [49]:
df.dropna(inplace=True)

In [50]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64